phrase = "peter cock"
print(phrase + "is cool")
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print (phrase.index("z"))
print(phrase.replace("peter", "tom" ))